"""Archive validated native render outputs for offline comparison.
The website gallery is generated by npm run gallery with CampusViewer.
"""
from pathlib import Path
import hashlib
import json
from PIL import Image
ROOT=Path(__file__).resolve().parents[2]
RELEASE=ROOT/'result/web/release26'
records=json.loads((RELEASE/'gallery-manifest.json').read_text())
plan=json.loads((RELEASE/'gallery-plan.json').read_text())
expected={r['name'] for r in plan}|{'campus'}
assert {r['name'] for r in records}==expected,'Gallery rendering is incomplete'
catalogue=json.loads((ROOT/'web/public/models/catalogue.json').read_text())
archive=RELEASE/'native-gallery';archive.mkdir(exist_ok=True)
output=[]
for record in records:
 assert record['sourceModelSha256']==catalogue['sourceModelSha256']
 source=RELEASE/'renders'/(record['name']+'.png')
 target=archive/(record['name']+'.webp')
 with Image.open(source) as image:
  assert image.width>=1000 and image.height>=800
  image.convert('RGB').save(target,quality=92,method=6)
 data=target.read_bytes()
 output.append({**record,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
(archive/'gallery-manifest.json').write_text(json.dumps({'version':'26','sourceModelSha256':catalogue['sourceModelSha256'],'images':output},indent=2)+'\n')
print('Archived',len(output),'native images; website gallery unchanged')
